package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.util.ItemFineRate
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.bo.PatronBillPayment



rule "FINES_ALL_65"
agenda-group "fine validation"
activation-group "fine validation"
when

$f: ItemFineRate()

$i: OleItemRecordForCirc(getItemType() in ("65"))

then
$f.setFineRate(1.00);
$f.setMaxFine(100.00);
$f.setInterval("H"); //Options are H-Hours; D-Days

 end

 rule "FINES_UGRAD_GRAD_01_03"
 agenda-group "fine validation"
 activation-group "fine validation"
 when

 $f: ItemFineRate()

 $i: OleItemRecordForCirc(getItemType() in ("01", "03"))

 $p: OlePatronDocument(getBorrowerTypeCode() in ("UGRAD","GRAD"))

 then
 $f.setFineRate(0.50);
 $f.setMaxFine(100.00);
 $f.setInterval("D"); //Options are H-Hours; D-Days

  end